### ISSUE TITLE
brave-core-ext-https-everywhere-update-publish is broken

### ISSUE THREAD

**Issue by fmarier** [brave/brave-core-crx-packager#70]
The `https-everywhere-builder-update-publish` Jenkins job no longer works after merging https://github.com/brave/https-everywhere-builder/pull/26. It fails with `Error: Cannot find module 'request-promise-native'` (see build 17).

The root cause appears to be an out-of-date `package-lock.json` file given the new dependencies introduced in https://github.com/brave/https-everywhere-builder/pull/26. In a fresh `brave/brave-core-crx-packager` clone, I get the following diff after running `npm install`:

```
diff --git a/package-lock.json b/package-lock.json
index dd9f592..207c2fb 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1367,6 +1367,7 @@
       "requires": {
         "commander": "^2.11.0",
         "level": "^5.0.1",
+        "request": "^2.88.0",
         "s3-client": "^4.4.2"
       }
     },
```

The build fails at this point, but if I run `npm install` again, I get a larger diff:

```
diff --git a/package-lock.json b/package-lock.json
index dd9f592..11fee36 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -35,7 +35,7 @@
       "from": "github:brave/ad-block",
       "requires": {
         "bloom-filter-cpp": "^1.2.2",
-        "hashset-cpp": "^2.1.1",
+        "hashset-cpp": "^2.2.1",
         "nan": "^2.13.2"
       },
       "dependencies": {
@@ -1367,6 +1367,8 @@
       "requires": {
         "commander": "^2.11.0",
         "level": "^5.0.1",
+        "request": "^2.88.0",
+        "request-promise-native": "^1.0.7",
         "s3-client": "^4.4.2"
       }
     },
@@ -2524,6 +2526,24 @@
         "uuid": "^3.3.2"
       }
     },
+    "request-promise-core": {
+      "version": "1.1.2",
+      "resolved": "https://registry.npmjs.org/request-promise-core/-/request-promise-core-1.1.2.tgz",
+      "integrity": "sha512-UHYyq1MO8GsefGEt7EprS8UrXsm1TxEvFUX1IMTuSLU2Rh7fTIdFtl8xD7JiEYiWU2dl+NYAjCTksTehQUxPag==",
+      "requires": {
+        "lodash": "^4.17.11"
+      }
+    },
+    "request-promise-native": {
+      "version": "1.0.7",
+      "resolved": "https://registry.npmjs.org/request-promise-native/-/request-promise-native-1.0.7.tgz",
+      "integrity": "sha512-rIMnbBdgNViL37nZ1b3L/VfPOpSi0TqVDQPAvO6U14lMzOLrt5nilxCQqtDKhZeDiW0/hkCXGoQjhgJd/tCh6w==",
+      "requires": {
+        "request-promise-core": "1.1.2",
+        "stealthy-require": "^1.1.1",
+        "tough-cookie": "^2.3.3"
+      }
+    },
     "require-directory": {
       "version": "2.1.1",
       "resolved": "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz",
@@ -2881,6 +2901,11 @@
         }
       }
     },
+    "stealthy-require": {
+      "version": "1.1.1",
+      "resolved": "https://registry.npmjs.org/stealthy-require/-/stealthy-require-1.1.1.tgz",
+      "integrity": "sha1-NbCYdbT/SfJqd35QmzCQoyJr8ks="
+    },
     "streamsink": {
       "version": "1.2.0",
       "resolved": "https://registry.npmjs.org/streamsink/-/streamsink-1.2.0.tgz",
```

and this time the build works.

**Comment by fmarier** [comment]
Here's the difference in the output of `npm list` between the first `npm install` and the second `npm install`:

```
--- /tmp/before    2019-08-14 17:18:13.626199295 -0700
+++ /tmp/after    2019-08-14 17:08:08.327372166 -0700
@@ -179,7 +179,11 @@
 │ ├── commander@2.20.0 deduped
 │ ├── level@5.0.1 deduped
 │ ├── request@2.88.0 deduped
-│ ├── UNMET DEPENDENCY request-promise-native@^1.0.7
+│ ├─┬ request-promise-native@1.0.7
+│ │ ├─┬ request-promise-core@1.1.2
+│ │ │ └── lodash@4.17.15 deduped
+│ │ ├── stealthy-require@1.1.1
+│ │ └── tough-cookie@2.4.3 deduped
 │ └─┬ s3-client@4.4.2
 │   ├── aws-sdk@2.496.0 deduped
 │   ├─┬ fd-slicer@1.1.0
```
